require File.expand_path('../config/application', __FILE__)

Dummy::Application.load_tasks

require 'jasmine-rails'
require 'bower-rails'
namespace :test do
  task :javascripts => 'spec:javascript'
end
