# path to parent directory of spec_files
# relative path from Rails.root
# defaults to spec/javascripts
spec_dir: ../javascripts/

# list of file expressions to include as specs into spec runner
# relative path from spec_dir
spec_files:
  - "**/*_test.js"

# path to directory of temporary files
# (spec runner and asset cache)
# defaults to spec/tmp
tmp_dir: "tmp"
